CREATE TABLE PROPERTY_TYPE
(
	Type		VARCHAR(12)		PRIMARY KEY
);

CREATE TABLE INVOICE_TYPE
(
	Type		VARCHAR(12)		PRIMARY KEY
);

CREATE TABLE LANDLORD
(
	Id			INT				PRIMARY KEY, 
    Name		VARCHAR(50)		NOT NULL, 
	Street		VARCHAR(50)		NOT NULL,
    City		VARCHAR(50)		NOT NULL, 
    State		VARCHAR(50)		NOT NULL, 
    Zip			INT				NOT NULL, 
    Phone		CHAR(10)		NOT NULL, 
    Email		VARCHAR(50)		NOT NULL
);


CREATE TABLE PROPERTY
(
	Id			INT				PRIMARY KEY,
	Lord_ID		INT,
	Street		VARCHAR(50) 	NOT NULL,
	City		VARCHAR(50) 	NOT NULL,
	State		VARCHAR(50) 	NOT NULL,
	Zip 		INT 			NOT NULL,
	Value 		INT,
	Description VARCHAR(255),
	Type 		VARCHAR(12),
	CONSTRAINT PROPERTY_LANDLORD_FK
	FOREIGN KEY(Lord_ID) REFERENCES LANDLORD(Id) ON DELETE SET NULL,
	CONSTRAINT PROPERTY_PROPTYPE_FK
	FOREIGN KEY(Type) REFERENCES PROPERTY_TYPE(Type) ON DELETE SET NULL
);


CREATE TABLE LEASE
(
	Id			INT 			PRIMARY KEY,
	Prop_ID 	INT 			NOT NULL,
	Start_date 	DATE,
	Duration_months INT,
	Monthly_rent FLOAT,
	CONSTRAINT LEASE_PROPERTY_FK
	FOREIGN KEY(Prop_ID) REFERENCES PROPERTY(Id) ON DELETE CASCADE
);


CREATE TABLE TENANT
(
    ID 			INT 			PRIMARY KEY,
	Prop_ID 	INT,
	Name 		VARCHAR(30) 	NOT NULL,
	Phone 		CHAR(10),
	Email 		VARCHAR(30),
	Registration_date DATE		NOT NULL,
	CONSTRAINT TENANT_PROPERTY_FK
	FOREIGN KEY(Prop_ID) REFERENCES PROPERTY(Id) ON DELETE SET NULL
);


CREATE TABLE INVOICE
(
	Id 			INT 			PRIMARY KEY,
	Prop_ID 	INT,
	Date_issued DATE,
	Date_paid 	DATE,
	Description VARCHAR(255),
	Cost 		FLOAT,
	Type 		VARCHAR(12),
	CONSTRAINT INVOICE_PROPERTY_FK
	FOREIGN KEY(Prop_ID) REFERENCES PROPERTY(Id),
	CONSTRAINT INVOICE_INVTYPE_FK
	FOREIGN KEY(Type) REFERENCES INVOICE_TYPE(Type) ON DELETE SET NULL
);

